- name: Install Rofi
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - rofi
    state: present

- name: Ensure sudoers.d path exists
  file: path=~/.config/rofi state=directory

- name: Copy Rofi Config
  ansible.builtin.copy:
    src: files/.config/rofi/config.rasi
    dest: ~/.config/rofi/config.rasi
    mode: '0644'

- name: Copy Rofi Theme
  ansible.builtin.copy:
    src: files/.config/rofi/theme.rasi
    dest: ~/.config/rofi/theme.rasi
    mode: '0644'
  