---
- hosts: localhost
  connection: local
  become: true

  include_tasks: create_ansible_user.yml
  include_tasks: create_main_user.yml

  vars_prompt:
    - name: main_user_password
      prompt: Type a password for the user '{{ main_user }}'.
      private: yes
      unsafe: yes
      encrypt: bcrypt
      confirm: yes
