---
- hosts: localhost
  connection: local
  become: true
  roles:
    - common

  tasks:
    - name: Register the username of the user running the playbook
      become: false
      local_action: command whoami
      register: main_user
      failed_when: "main_user == 'root'"
