---
- hosts: localhost
  connection: local
  become: true
  roles:
    - common
  vars:
    - ansible_user: ansible
    - bootloader: grub
    - networkmanager: networkmanager
    - display_server: xorg
    - sound_server: pipewire
    - graphics_driver: nvidia
    - window_manager: awesome
    - compositor: xcompmgr
    - terminal: kitty
    - aur_helper: yay
    - filemanager: thunar
    - displaymanager: ly
    - image_viewer: feh

  vars_prompt:
    - name: main_user
      prompt: Type a username for your main sudo user.
      private: no
    - name: main_user_password
      prompt: Type a password for your main sudo user.
      private: yes
      unsafe: yes
      encrypt: bcrypt
      confirm: yes
