---
- hosts: localhost
  connection: local
  become: true
  vars:
    - main_user: maroka
    - ansible_user: ansible
    - terminal: kitty


  tasks:
  - include_tasks: ansible-user.yml
  
  - name: Install Packages
    community.general.pacman:
      name:
        - btop
        - flameshot
        - chromium
        - firefox
        - zathura
        - zathura-pdf-mupdf
        - catfish
        - feh
      state: present

  - name: Install and Configure Terminal
    # Install Packages
    community.general.pacman:
      name:
        - "{{ terminal }}"

  - name: Install Thunar
    community.general.pacman:
      name:
        - thunar
        - gvfs
        - thunar-media-tags-plugin
        - tumbler
        - raw-thumbnailer
      state: present

  - name: Configure Thunar
    # Add Custom Actions
    ansible.builtin.template:
      src: files/thunar/custom_actions.xml.j2
      dest: "/home/{{ main_user }}/.config/Thunar/uca.xml"
      owner: "{{ main_user }}"
      group: "{{ main_user }}"
