---
- hosts: localhost
  connection: local
  become: true
  roles:
    - common
  vars:
    - ansible_user: ansible
    - terminal: kitty

  vars_prompt:
  - name: main_user
    prompt: Type a username for your main sudo user.
    private: no
  - name: main_user_password
    prompt: Type a password for your main sudo user.
    private: yes
    unsafe: yes
    encrypt: bcrypt
    confirm: yes
