---
- hosts: localhost
  connection: local
  become: true
  vars:
    - main_user: maroka
    - ansible_user: ansible
    - terminal: kitty


  tasks:
  - name: Install collections
    community.general.ansible_galaxy_install:
      type: collection
      requirements_file: requirements.yml

  - name: Install git & base-devel
    community.general.pacman:
      name:
        - git
        - base-devel
      state: present
  
  - name: Install Yay
    become_user: "{{ ansible_user }}"
    ansible.builtin.command: git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si && rm -r yay-bin
  
  - name: Upgrade the System
    kewlfft.aur.aur:
      upgrade: yes
      use: yay

  - name: Install Packages
    community.general.pacman:
      name:
        - sudo
        - cronie
        - btop
        - flameshot
        - chromium
        - firefox
        - zathura
        - zathura-pdf-mupdf
        - catfish
        - feh
      state: present

  - name: Start and Enable cronie
    ansible.builtin.service:
      name: cronie
      state: started
      enabled: yes

  # Set up ansible sudo system user
  - include_tasks: ansible-user.yml  

  - name: Install and Configure Terminal
    # Install Packages
    community.general.pacman:
      name:
        - "{{ terminal }}"

  - name: Install Thunar
    kewlfft.aur.aur:
      use: yay
      name:
        - thunar
        - gvfs
        - thunar-media-tags-plugin
        - tumbler
        - raw-thumbnailer
      state: present

  - name: Configure Thunar
    # Add Custom Actions
    ansible.builtin.template:
      src: files/thunar/custom_actions.xml.j2
      dest: "/home/{{ main_user }}/.config/Thunar/uca.xml"
      owner: "{{ main_user }}"
      group: "{{ main_user }}"

  - name: Add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: "{{ ansible_user }}"
      minute: "*/10"
      job: ansible-pull -o -U git@github.com:Maroka-chan/ansible-desktop.git
