---
- hosts: localhost
  connection: local
  become: true
  roles:
    - common
  vars:
    - ansible_user: ansible
    - terminal: kitty

  tasks:
  - name: Install collections
    community.general.ansible_galaxy_install:
      type: collection
      requirements_file: requirements.yml
