---
- hosts: localhost
  connection: local
  become: true
  roles:
    - common
  vars:
    ansible_user: ansible
    bootloader: grub
    display_server: xorg
    sound_server: pipewire
    graphics_driver: nvidia
    window_managers:
      - awesome
    compositor: xcompmgr
    terminal: kitty
    aur_helper: yay
    filemanager: thunar
    displaymanager: ly
    image_viewer: feh
    keyring: gnome-keyring
    application_launcher: rofi

  vars_prompt:
    - name: main_user
      prompt: Type a username for your main sudo user.
      private: no
      confirm: yes
    - name: main_user_password
      prompt: Type a password for your main sudo user.
      private: yes
      unsafe: yes
      encrypt: bcrypt
      confirm: yes
