---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Register the username of the user running the playbook
      become: false
      local_action: command whoami
      register: main_user
      failed_when: "main_user == 'root'"
  roles:
    - common

  tasks:
    - name: Print finish message
      ansible.builtin.debug:
        msg: Done! You may now reboot.