- name: Add main user
  user:
    name: "{{ main_user }}"

- name: Set up sudo for main user
  ansible.builtin.template:
    src: "files/sudoer_{{ main_user }}"
    dest: "/etc/sudoers.d/{{ main_user }}"
    owner: root
    group: root
    mode: 0440
