- name: Install Xorg
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - xorg-server
    state: present
  become: yes

- name: Copy xprofile
  ansible.builtin.copy:
    src: files/.xprofile
    dest: ~/
    mode: '0644'
  