- name: Install Xorg
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - xorg-server
    state: present
  become: yes
  become_user: "{{ ansible_user }}"

- name: Copy xprofile
  ansible.builtin.copy:
    src: files/.xprofile
    dest: ~/
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0644'
  become: yes
  become_user: "{{ main_user }}"
  