- name: Install Xorg
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - xorg-server
    state: present

- name: Copy xprofile
  ansible.builtin.copy:
    src: files/.xprofile
    dest: ~/
    mode: '0644'
  
  // Setup xorg.conf.d keyboard and wacom etc.

  // TODO
  // - Install texlive n stuff for knap
  // - Move .config and other dotfiles into dotfiles repo