- name: Install GNOME keyring
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - gnome-keyring
      - libsecret
      - seahorse
    state: present
  become: yes
  become_user: "{{ ansible_user }}"