- name: Install Awesome
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - awesome-git
    state: present
  become: yes
  become_user: "{{ ansible_user }}"

- name: Copy Awesome config from dotfiles
  ansible.builtin.copy:
    src: files/dotfiles/config/awesome
    dest: ~/.config/
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
  become: yes
  become_user: "{{ main_user }}"