- name: Install Awesome
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - awesome-git
    state: present
  become: yes

- name: Synchronize Awesome config from dotfiles
  ansible.posix.synchronize:
    src: files/dotfiles/config/awesome
    dest: ~/.config