- name: Install Pipewire
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - wireplumber
      - lib32-pipewire
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - lib32-pipewire-jack
      - pipewire
    state: present
