- name: Install git & base-devel
  community.general.pacman:
    name:
      - git
      - base-devel
    state: present
  become: yes

- name: Clone Yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: /tmp/yay-bin
    update: true

- name: Install Yay
  command:
    chdir: /tmp/yay-bin
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
