- name: Enable NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    enabled: yes
  become: yes

- name: Start NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: started
  become: yes
