- name: Enable NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    enabled: yes

- name: Start NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: started
