- name: Install Thunar
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - thunar
      - gvfs
      - thunar-media-tags-plugin
      - tumbler
      - raw-thumbnailer
    state: present
  become: yes
  
- name: Ensure Thunar Config Dir Exists
  file: path=~/.config/Thunar state=directory mode=0700

- name: Add Custom Actions to Thunar
  ansible.builtin.template:
    src: thunar/custom_actions.xml.j2
    dest: ~/.config/Thunar/uca.xml
    mode: '0600'
