- name: Install Thunar
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - thunar
      - gvfs
      - thunar-media-tags-plugin
      - tumbler
      - raw-thumbnailer
    state: present
  become: yes
  become_user: "{{ ansible_user }}"
  

- name: Create Thunar Config Dir
  file: path=~/.config/Thunar state=directory mode=0700
  become: yes
  become_user: "{{ main_user }}"

- name: Add Custom Actions to Thunar
  ansible.builtin.template:
    src: thunar/custom_actions.xml.j2
    dest: ~/.config/Thunar/uca.xml
  become: yes
  become_user: "{{ main_user }}"
