- name: Copy preconfigured mkinitcpio config
  ansible.builtin.copy:
    src: files/mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Generate GRUB config
