- include: compare_default_file.yml
  with_items:
    - /etc/sudoers


- name: Copy preconfigured sudoers file
  ansible.builtin.copy:
    src: files/sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: '0440'
  become: yes