- name: Ensure wallpaper dir exists
  file: path=~/Pictures/Wallpapers state=directory
  become: yes
  become_user: "{{ main_user }}"

- name: Synchronize wallpapers
  ansible.posix.synchronize:
    src: files/dotfiles/wallpapers
    dest: ~/Pictures/Wallpapers
  become: yes
  become_user: "{{ main_user }}"