vars_prompt: 
  - name: username
    prompt: Type a username for your main sudo user. 
    private: no                                                                                                                           
  - name: password                         
    prompt: Type a password for your main sudo user.  
    private: yes                                                                                                                          
    unsafe: yes  
    encrypt: bcrypt          
    confirm: yes
    salt_size: 64

- name: Check that the wheel group exists
  group:
    name: wheel
    state: present

- name: Add wheel user
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    groups: wheel
    append: yes
