- name: Install Base Packages
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - btop
      - neovim
      - chromium
      - firefox
      - neofetch
      - man-db
      - curl
      - jq
      - rsync
    state: present
  become: yes
  become_user: "{{ ansible_user }}"
