- name: Install Fonts
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - ttf-merriweather
      - ttf-google-fonts-git
      - ttf-vlgothic
    state: present
  become: yes


# Caskaydia nerd font
- name: Ensure Caskaydia font dir exists
  file: path=/usr/share/fonts/caskaydia-cove-nerd-font state=directory
  become: yes

- name: Download patched Caskaydia nerd font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Regular%20Nerd%20Font%20Complete.otf
    dest: /usr/share/fonts/caskaydia-cove-nerd-font/Caskaydia_Cove_Regular_Nerd_Font_Complete.otf
    mode: '0644'
  become: yes

- name: Download patched Mono Caskaydia nerd font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Regular%20Nerd%20Font%20Complete%20Mono.otf
    dest: /usr/share/fonts/caskaydia-cove-nerd-font/Caskaydia_Cove_Regular_Nerd_Font_Complete_Mono.otf
    mode: '0644'
  become: yes
