---
- name: Install Sudo
  community.general.pacman:
    name:
      - sudo
    state: present

- include_tasks: create_ansible_user.yml

- include_tasks: enable_wheel_group.yml
- include_tasks: create_wheel_user.yml

- include_tasks: aur_helper/{{ aur_helper }}.yml
- include_tasks: upgrade_system.yml
- include_tasks: install_base_packages.yml

- include_tasks: terminal_emulator/{{ terminal }}.yml
- include_tasks: filemanager/{{ filemanager }}.yml
- include_tasks: displaymanager/{{ displaymanager }}.yml