---
- name: Ensure bootloader is present
  ansible.builtin.command: pacman -Q {{ bootloader }}
  register: command_result
  failed_when: "'was not found' in command_result.stderr"

- include_tasks: bootloader/{{ bootloader }}.yml
- include_tasks: configure_profile.yml


### Set up Sudo ###

- name: Ensure Sudo is present
  community.general.pacman:
    name:
      - sudo
    state: present
  become: yes

- include_tasks: configure_sudoers.yml

# ===================== #


### Configure Pacman and AUR helper ###

- include_tasks: aur_helper/{{ aur_helper }}.yml
- include_tasks: configure_pacman.yml
- include_tasks: upgrade_system.yml

# =================================== #


### Install before other packages to avoid conflicts ###

- include_tasks: sound_server/{{ sound_server }}.yml
- include_tasks: compositor/{{ compositor }}.yml

# =================================================== #


- include_tasks: install_fonts.yml
- include_tasks: install_packages.yml
- include_tasks: copy_wallpapers.yml


### Install Keyring ###

- include_tasks: keyring/{{ keyring }}.yml

# =================== #


### Install Display Server ###

- include_tasks: display_server/{{ display_server }}.yml

# ========================== #


### Install Window Managers ###

- include_tasks: window_manager/{{ item }}.yml
  loop: "{{ window_managers }}"

# =========================== #


### Install Graphics Drivers ###

- include_tasks: graphics_drivers/nvidia.yml
  when: "'nvidia' in graphics_driver"

# ============================ #


### Install Applications ###

- include_tasks: terminal_emulator/{{ terminal }}.yml
- include_tasks: application_launcher/{{ application_launcher }}.yml
- include_tasks: filemanager/{{ filemanager }}.yml
- include_tasks: displaymanager/{{ displaymanager }}.yml
- include_tasks: image_viewer/{{ image_viewer }}.yml

# ======================== #


- name: Print finish message
  ansible.builtin.debug:
    msg: Done! You may now reboot.
