- name: Install Kitty
  kewlfft.aur.aur:
    name: kitty
    use: "{{ aur_helper }}"
    state: present
  become: yes
  become_user: "{{ ansible_user }}"

- name: Ensure Config Dir Exists
  file: path=~/.config/kitty state=directory
  become: yes
  become_user: "{{ main_user }}"

- name: Copy Kitty Config
  ansible.builtin.copy:
    src: files/.config/kitty/kitty.conf
    dest: ~/.config/kitty/kitty.conf
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0644'
  become: yes
  become_user: "{{ main_user }}"
  