- name: Install Kitty
  kewlfft.aur.aur:
    name: kitty
    use: "{{ aur_helper }}"
    state: present

- name: Ensure Config Dir Exists
  file: path=~/.config/kitty state=directory

- name: Copy Kitty Config
  ansible.builtin.copy:
    src: files/.config/kitty/kitty.conf
    dest: ~/.config/kitty/kitty.conf
    mode: '0644'
  