- name: Install feh
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - feh
    state: present
  become: yes

- name: Copy fehbg script
  ansible.builtin.template:
    src: feh/.fehbg.j2
    dest: ~/.fehbg
    mode: '0754'