- name: Install feh
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - feh
    state: present
  become: yes
  become_user: "{{ ansible_user }}"

- name: Copy fehbg script
  ansible.builtin.template:
    src: feh/.fehbg.j2
    dest: ~/.fehbg
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: '0754'
  become: yes
  become_user: "{{ main_user }}"