- name: Ensure GRUB is present
  community.general.pacman:
    name:
      - grub
      - efibootmgr
    state: present
  become: yes

- name: Include GRUB vars
  ansible.builtin.include_vars: "{{ bootloader }}_vars.yml"

- name: Run grub-install
  ansible.builtin.command:
    cmd: grub-install --target={{ target }} --efi-directory={{ efi_dir }} --bootloader-id={{ bootloader_id }}
  become: yes

- name: Copy preconfigured GRUB config
  ansible.builtin.copy:
    src: files/grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Generate GRUB config
