- name: Copy preconfigured GRUB config
  ansible.builtin.copy:
    src: files/grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Generate GRUB config
